name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Generate version
        id: version
        run: |
          # 如果是标签推送，使用标签作为版本号
          if ("${{ github.event_name }}" -eq "push" -and "${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            # 否则使用短SHA作为版本号
            $version = "dev-$(git rev-parse --short HEAD)"
          }
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Build with PyInstaller
        run: |
          # 直接构建到带有版本号的目录，避免重命名问题
          $outputDir = "android-flashtool-AFC_${{ env.version }}_windows_x64"
          
          # 使用 --distpath 和 --name 参数直接指定输出路径和名称
          pyinstaller --noconfirm --onedir --console --add-data "commands;commands/" --distpath "dist/$outputDir" --name "android-flashtool" main.py
          
          # 创建ZIP压缩包
          Compress-Archive -Path "dist/$outputDir" -DestinationPath "dist/$outputDir.zip"
          
          echo "Build completed successfully"
          echo "Output directory: dist/$outputDir"
          echo "ZIP package: dist/$outputDir.zip"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-flashtool-AFC-${{ env.version }}-windows-x64
          path: dist/android-flashtool-AFC_${{ env.version }}_windows_x64.zip
          retention-days: 7

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}
            
            ### What's new:
            - Automated build with GitHub Actions
            - Windows 64-bit executable
            
            ### Changes:
            - See commit history for details
            
            ### Assets:
            - Windows 64-bit: `android-flashtool-AFC_${{ env.version }}_windows_x64.zip`
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/android-flashtool-AFC_${{ env.version }}_windows_x64.zip
          asset_name: android-flashtool-AFC_${{ env.version }}_windows_x64.zip
          asset_content_type: application/zip